version: "3.9"
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    container_name: streamlit-dev
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    ports:
      - "8501:8501"  # streamlit
    command: sleep infinity


volumes:
  pgdata:

